<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>/README.md</PackageReadmeFile>
    <IncludeContentInPack>true</IncludeContentInPack>
    <RepositoryUrl>https://github.com/ViniciusMarchand/SENFF_NUGET_RABBITMQ</RepositoryUrl>
    <RepositoryType>git</RepositoryType>


    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>SenffTest.Messaging.RabbitMQ</PackageId>
    <Version>1.0.6</Version>
    <Authors>ViniciusMarchand</Authors>
    <Company>ViniciusMarchand</Company>
    <Description>Message library with RabbitMQ.</Description>
    <PackageTags>rabbitmq messaging queue</PackageTags>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <IncludeSymbols>true</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    <PackageReference Include="SenffTest.Messaging.RabbitMQ.Abstraction" Version="1.0.0" />
    <None Include="README.md" pack="true" PackagePath="." />
  </ItemGroup>

</Project>
